apiVersion: v1
kind: Service
metadata:
  name: deepak-demo-app
  labels:
    app: webapp
  namespace: dk
spec:
  type: {{ .Values.service.type }}
  ports:
    - port:  {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: webapp
