---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deepak-demo-app-local
  namespace: argocd
  labels:
    environment: local
    region: kind
    app: deepak-demo-app
spec:
  destination:
    name: in-cluster
    namespace: dk
  project: deepak-demo-app
  source:
    helm:
      valueFiles:
      - values.yaml
    path: chart/
    repoURL: https://github.com/sentinelleader/demo-app
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
