---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: deepak-demo-app
  namespace: argocd
spec:
  destinations:
  - namespace: dk
    server: '*'
  - namespace: monitoring
    server: '*'
  orphanedResources:
    warn: true
  sourceRepos:
  - https://github.com/sentinelleader/demo-app
